openapi: 3.0.3
info:
  title: Device Geofencing Subscriptions
  description: |
    API to create, retrieve and delete event subscriptions to realize geofencing for a user device.

    # Introduction

    With this API, API consumers can create subscriptions for their devices to receive notifications when a device enters or exits a specified area.

    * If the provided area is out of the operator's coverage or it is not supported for any reason, an error `422 GEOFENCING_SUBSCRIPTIONS.AREA_NOT_COVERED` will be returned.
    * Legal restrictions regarding privacy, or other regulatory or implementation issues, may force the operator to set restrictions to the provided area, such as setting a minimum value to the accepted radius. In these cases, an error `422 GEOFENCING_SUBSCRIPTIONS.INVALID_AREA` will be returned and the error message will refer to the reason of the limitation.

    The area provided in the request is described by a circle determined by coordinates (latitude and longitude) and an accuracy defined by the radius.

    Upon successfully creating a subscription, the API will provide an Event Subscription ID, and it will indicate the subscription's expiration date.

    If the geofencing-state of a device changes, the event subscriber will be notified back to the provided Notification-Url given by the subscription-request.

    Device geofencing API could be useful in scenarios such as:

    - Tracking devices for Presetting of Home-Settings
    - Tracking of logistics

    # Relevant terms and definitions

    * **Device**: A device refers to any physical entity that can connect to a network and participate in network communication.

    * **Area**: It specifies the geographical surface which a device is planned to enter or exit.

    # API Functionality

    The API exposes following capabilities:

    ## Device Geofencing subscription
    These endpoints allow to manage event subscription on geofencing device location event.

    The CAMARA subscription model is detailed in the CAMARA API design guideline document and follows CloudEvents specification.

    It is mandatory in the subscription to provide the event `type` for which the client would like to subscribe.

    Following event ``types`` are managed for this API:
      - ``org.camaraproject.geofencing-subscriptions.v0.area-entered``  - Event triggered when the device enters the given area

      - ``org.camaraproject.geofencing-subscriptions.v0.area-left``     - Event triggered when the device leaves the given area

    Note: Additionally, the following events could be send, which do not require a dedicated subscription:
      - `org.camaraproject.geofencing-subscriptions.v0.subscription-started` is sent when the subscription starts.
      - `org.camaraproject.geofencing-subscriptions.v0.subscription-updated` is sent when the subscription is updated.
      - `org.camaraproject.geofencing-subscriptions.v0.subscription-ended` is sent when the subscription ends.

    It is used when:
      - the subscription expire time (optionally set by the requester) has been reached
      - the maximum number of subscription events (optionally set by the requester) has been reached
      - the subscription was deleted by the requester
      - the Access Token `sinkCredential` (optionally set by the requester) expiration time has been reached
      - the API server has to stop sending notification prematurely
      - the specified geofence-`area` cannot be covered or is too small to be managed

    ### Notification callback

    This endpoint describes the event notification received on subscription listener side when the event occurred.
    As for subscription, detailed description of the event notification is provided in the CAMARA API design guideline document.

    _**WARNING**: This callback endpoint must be exposed on the consumer side as `POST /{$request.body#/sink}`.
      Developers may provide a callback URL on which notifications regarding geofencing can be received from the service provider.
      If an event occurs the application will send events to the provided webhook - 'sink'._

    <!-- CAMARA:MANDATORY:authorization-and-authentication:BEGIN -->
    # Authorization and authentication

    The "Camara Security and Interoperability Profile" provides details of how an API consumer requests an access token. Please refer to Identity and Consent Management (https://github.com/camaraproject/IdentityAndConsentManagement/) for the released version of the profile.

    The specific authorization flows to be used will be agreed upon during the onboarding process, happening between the API consumer and the API provider, taking into account the declared purpose for accessing the API, whilst also being subject to the prevailing legal framework dictated by local legislation.

    In cases where personal data is processed by the API and users can exercise their rights through mechanisms such as opt-in and/or opt-out, the use of three-legged access tokens is mandatory. This ensures that the API remains in compliance with privacy regulations, upholding the principles of transparency and user-centric privacy-by-design.
    <!-- CAMARA:MANDATORY:authorization-and-authentication:END -->

    <!-- CAMARA:MANDATORY:identifying-device-from-access-token:BEGIN -->
    # Identifying the device from the access token

    This API requires the API consumer to identify a device as the subject of the API as follows:
    - When the API is invoked using a two-legged access token, the subject will be identified from the optional `device` object, which therefore MUST be provided.
    - When a three-legged access token is used however, this optional identifier MUST NOT be provided, as the subject will be uniquely identified from the access token.

    This approach simplifies API usage for API consumers using a three-legged access token to invoke the API by relying on the information that is associated with the access token and was identified during the authentication process.

    ## Error handling:

    - If the subject cannot be identified from the access token and the optional `device` object is not included in the request, then the server will return an error with the `422 MISSING_IDENTIFIER` error code.

    - If the subject can be identified from the access token and the optional `device` object is also included in the request, then the server will return an error with the `422 UNNECESSARY_IDENTIFIER` error code. This will be the case even if the same device is identified by these two methods, as the server is unable to make this comparison.
    <!-- CAMARA:MANDATORY:identifying-device-from-access-token:END -->

    # Multi-SIM scenario handling

    In multi-SIM scenarios, where more than one mobile device is associated with the phone number given as input in the API call (e.g. a smartphone with an associated smartwatch), it might not be possible to uniquely identify the device whose location is to be verified. Check with the API provider what is the expected behaviour when a phone number belonging to a multi-SIM group is used as the device identifier, as the API may behave:

    - rejecting the subscription with an error indicating that that phone number is not supported for this API, or
    - generating events for a single device in the multi-SIM group, if one of the devices is considered linked to the main SIM and this concept is supported by the operator, or
    - generating events for of all the SIMs associated to the requested phone number.

    Possible solutions to make the scenario more deterministic include:

    - Using preferably the authorisation code flow to obtain an access token, which will automatically identify the intended device.
    - Identifying the intended device from a unique identifier for that device, such as its source IP address and port.
    - Check with the API provider whether a unique "secondary" phone number is already associated with each device and use the secondary phone number to identify the intended device if available.

    <!-- CAMARA:MANDATORY:additional-error-responses:BEGIN -->
    # Additional CAMARA error responses

    The list of error codes in this API specification is not exhaustive. Therefore the API specification MAY not document some non-mandatory error statuses as indicated in `CAMARA API Design Guide`.

    Please refer to the `CAMARA_common.yaml` of the Commonalities Release associated to this API version for a complete list of error responses. The applicable Commonalities Release can be identified in the `API Readiness Checklist` document associated to this API version.

    As a specific rule, error `501 - NOT_IMPLEMENTED` can be only a possible error response if it is explicitly documented in the API.
    <!-- CAMARA:MANDATORY:additional-error-responses:END -->

    <!-- CAMARA:MANDATORY:request-body-strictness:BEGIN -->
    # Request body strictness

    This API rejects requests with JSON request bodies that contain properties not declared in this specification, at any nesting level. Unknown properties result in a `400 INVALID_ARGUMENT` response.
    <!-- CAMARA:MANDATORY:request-body-strictness:END -->

    # Further info and support

    (FAQs will be added in a later version of the documentation)

  version: wip
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-camara-commonalities: 0.8.0
externalDocs:
  description: Project documentation at Camara
  url: https://github.com/camaraproject/DeviceLocation

servers:
  - url: "{apiRoot}/geofencing-subscriptions/vwip"
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root

tags:
  - name: Geofencing Subscriptions
    description: Operations to manage event subscriptions on geofencing events for leaving and entering an area.
paths:
  /subscriptions:
    post:
      tags:
        - Geofencing Subscriptions
      summary: "Create a geofencing subscription for a device"
      description: Create a subscription for a device to receive notifications when the device enters or exits a specified area.
      operationId: createGeofencingSubscription
      parameters:
        - $ref: "#/components/parameters/x-correlator"
      security:
        - openId:
            - geofencing-subscriptions:org.camaraproject.geofencing-subscriptions.v0.area-entered:create
            - geofencing-subscriptions:org.camaraproject.geofencing-subscriptions.v0.area-left:create
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubscriptionRequest"
            examples:
              CIRCLE_AREA_ENTERED:
                $ref: "#/components/examples/REQUEST_CIRCLE_AREA_ENTERED"
              REQUEST_CIRCLE_AREA_ENTERED_MULTIPLE_IDENTIFIERS:
                $ref: "#/components/examples/REQUEST_CIRCLE_AREA_ENTERED_MULTIPLE_IDENTIFIERS"
        required: true
      callbacks:
        notifications:
          "{$request.body#/sink}":
            post:
              summary: "notifications callback"
              description: |
                Important: This endpoint is to be implemented by the API consumer.
                The Geofencing server will call this endpoint whenever a Geofencing event occurs.
                The `operationId` value will have to be replaced accordingly with WG API specific semantics.
              operationId: postNotification
              parameters:
                - $ref: "#/components/parameters/x-correlator"
              requestBody:
                required: true
                content:
                  application/cloudevents+json:
                    schema:
                      $ref: "#/components/schemas/CloudEvent"
                    examples:
                      CIRCLE_AREA_ENTERED:
                        $ref: "#/components/examples/CIRCLE_AREA_ENTERED"
                      CIRCLE_AREA_LEFT:
                        $ref: "#/components/examples/CIRCLE_AREA_LEFT"
                      SUBSCRIPTION_STARTED:
                        $ref: "#/components/examples/SUBSCRIPTION_STARTED"
                      SUBSCRIPTION_UPDATED:
                        $ref: "#/components/examples/SUBSCRIPTION_UPDATED"
                      SUBSCRIPTION_ENDED:
                        $ref: "#/components/examples/SUBSCRIPTION_ENDED"
                      SUBSCRIPTION_UNPROCESSABLE:
                        $ref: "#/components/examples/SUBSCRIPTION_UNPROCESSABLE"
              responses:
                "204":
                  description: Successful notification.
                  headers:
                    x-correlator:
                      $ref: "#/components/headers/x-correlator"
                "400":
                  $ref: "#/components/responses/Generic400"
                "401":
                  $ref: "#/components/responses/Generic401"
                "403":
                  $ref: "#/components/responses/Generic403"
                "410":
                  $ref: "#/components/responses/Generic410"
                "429":
                  $ref: "#/components/responses/Generic429"
              security:
                - notificationsBearerAuth: []
                - {}
      responses:
        "201":
          description: Created (Successful creation of subscription).
          headers:
            x-correlator:
              $ref: "#/components/headers/x-correlator"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subscription"
        "202":
          description: Request accepted to be processed. It applies for async creation process.
          headers:
            x-correlator:
              $ref: "#/components/headers/x-correlator"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubscriptionAsync"
        "400":
          $ref: "#/components/responses/CreateSubscriptionBadRequest400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "422":
          $ref: "#/components/responses/CreateSubscriptionUnprocessableEntity422"
        "429":
          $ref: "#/components/responses/Generic429"
    get:
      tags:
        - Geofencing Subscriptions
      summary: "Retrieve a list of geofencing event subscription"
      description: Retrieve a list of geofencing event subscription(s).
      operationId: retrieveGeofencingSubscriptionList
      parameters:
        - $ref: "#/components/parameters/x-correlator"
      security:
        - openId:
            - geofencing-subscriptions:read
      responses:
        "200":
          description: List of event subscription details.
          headers:
            x-correlator:
              $ref: "#/components/headers/x-correlator"
          content:
            application/json:
              schema:
                type: array
                minItems: 0
                maxItems: 20
                items:
                  $ref: "#/components/schemas/Subscription"
        "400":
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
  /subscriptions/{subscriptionId}:
    get:
      tags:
        - Geofencing Subscriptions
      summary: "Operation to retrieve a subscription based on the provided ID"
      description: Retrieve Geofencing subscription information for a given subscription ID.
      operationId: retrieveGeofencingSubscription
      security:
        - openId:
            - geofencing-subscriptions:read
      parameters:
        - $ref: "#/components/parameters/SubscriptionId"
        - $ref: "#/components/parameters/x-correlator"
      responses:
        "200":
          description: OK
          headers:
            x-correlator:
              $ref: "#/components/headers/x-correlator"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subscription"
        "400":
          $ref: "#/components/responses/SubscriptionIdRequired"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"
    delete:
      tags:
        - Geofencing Subscriptions
      summary: "Delete a Geofencing event subscription"
      operationId: deleteGeofencingSubscription
      description: Delete a given Geofencing subscription.
      security:
        - openId:
            - geofencing-subscriptions:delete
      parameters:
        - $ref: "#/components/parameters/SubscriptionId"
        - $ref: "#/components/parameters/x-correlator"
      responses:
        "204":
          description: Geofencing subscription deleted.
          headers:
            x-correlator:
              $ref: "#/components/headers/x-correlator"
        "202":
          description: Request accepted to be processed. It applies for async deletion process.
          headers:
            x-correlator:
              $ref: "#/components/headers/x-correlator"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubscriptionAsync"
        "400":
          $ref: "#/components/responses/SubscriptionIdRequired"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"
components:
  securitySchemes:
    openId:
      description: OpenID Connect authentication.
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
    notificationsBearerAuth:
      $ref: '../common/CAMARA_event_common.yaml#/components/securitySchemes/notificationsBearerAuth'
  parameters:
    SubscriptionId:
      name: subscriptionId
      in: path
      description: Subscription identifier that was obtained from the create event subscription operation.
      required: true
      schema:
        $ref: "#/components/schemas/SubscriptionId"
    x-correlator:
      name: x-correlator
      in: header
      description: Correlation id for the different services.
      schema:
        $ref: '../common/CAMARA_common.yaml#/components/schemas/XCorrelator'
  headers:
    x-correlator:
      description: Correlation id for the different services.
      schema:
        $ref: '../common/CAMARA_common.yaml#/components/schemas/XCorrelator'
  schemas:
    XCorrelator:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/XCorrelator'
    ErrorInfo:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/ErrorInfo'

    SubscriptionRequest:
      description: The request for creating an event-type event subscription.
      type: object
      required:
        - sink
        - protocol
        - config
        - types
      properties:
        protocol:
          $ref: "#/components/schemas/Protocol"
        sink:
          type: string
          format: uri
          maxLength: 2048
          pattern: ^https:\/\/.+$
          description: The address to which events shall be delivered using the selected protocol.
          example: "https://endpoint.example.com/sink"
        sinkCredential:
          $ref: "#/components/schemas/SinkCredential"
        types:
          description: |
            Camara Event types which are eligible to be delivered by this subscription.
            Note: As of now we enforce to have only event type per subscription.
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: "#/components/schemas/SubscriptionEventType"
        config:
          $ref: "#/components/schemas/ConfigRequest"
      discriminator:
        propertyName: protocol
        mapping:
          HTTP: "#/components/schemas/HTTPSubscriptionRequest"

    Protocol:
      $ref: '../common/CAMARA_event_common.yaml#/components/schemas/Protocol'

    Config:
      description: |
        Implementation-specific configuration parameters are needed by the subscription manager for acquiring events.
        In CAMARA we have predefined attributes like `subscriptionExpireTime`, `subscriptionMaxEvents`, `initialEvent`.
      type: object
      properties:
        subscriptionExpireTime:
          type: string
          format: date-time
          maxLength: 64
          example: "2023-01-17T13:18:23.682Z"
          description: The subscription expiration time (in date-time format) requested by the API consumer. It must follow [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) and must have time zone.
        subscriptionMaxEvents:
          type: integer
          format: int32
          description: |
            Identifies the maximum number of event reports to be generated (>=1) requested by the API consumer - Once this number is reached, the subscription ends.
            Note on combined usage of `initialEvent` and `subscriptionMaxEvents`:
            If an event is triggered following `initialEvent` set to `true`, this event will be counted towards `subscriptionMaxEvents`.
          minimum: 1
          maximum: 1000000
          example: 5
        initialEvent:
          type: boolean
          description: |
            Set to `true` by API consumer if consumer wants to get an event as soon as the subscription is created and current situation reflects event request.
            Example: Consumer request area entered event. If consumer sets initialEvent to true and device is already in the geofence, an event is triggered.

    ConfigRequest:
      description: |
        Implementation-specific configuration parameters are needed by the subscription manager for acquiring events.
        In CAMARA we have predefined attributes like `subscriptionExpireTime`, `subscriptionMaxEvents`, `initialEvent`.
        Specific event type attributes requested by the client must be defined in `subscriptionDetail`.
        Note: If a request is performed for several event types, all subscribed events will use the same `config` parameters.
      allOf:
        - $ref: "#/components/schemas/Config"
        - type: object
          required:
            - subscriptionDetail
          properties:
            subscriptionDetail:
              $ref: "#/components/schemas/SubscriptionDetailRequest"

    ConfigResponse:
      description: |
        Implementation-specific configuration parameters are needed by the subscription manager for acquiring events.
        In CAMARA we have predefined attributes like `subscriptionExpireTime`, `subscriptionMaxEvents`, `initialEvent`.
        Specific event type attributes granted by the implementation are included in `subscriptionDetail`.
        Note: If a request is performed for several event types, all subscribed events will use the same `config` parameters.
      allOf:
        - $ref: "#/components/schemas/Config"
        - type: object
          required:
            - subscriptionDetail
          properties:
            subscriptionDetail:
              $ref: "#/components/schemas/SubscriptionDetailResponse"


    SubscriptionDetailRequest:
      description: The detail of the requested event subscription.
      type: object
      properties:
        device:
          $ref: "#/components/schemas/Device"
        area:
          $ref: "#/components/schemas/Area"
      required:
        - area

    SubscriptionDetailResponse:
      description: The detail of the event subscription granted by the implementation.
      type: object
      properties:
        device:
          $ref: "#/components/schemas/DeviceResponse"
        area:
          $ref: "#/components/schemas/Area"
      required:
        - area

    SubscriptionEventType:
      type: string
      description: |
        area-entered - Event triggered when the device enters the given area

        area-left - Event triggered when the device leaves the given area
      enum:
        - org.camaraproject.geofencing-subscriptions.v0.area-entered
        - org.camaraproject.geofencing-subscriptions.v0.area-left

    NotificationEventType:
      type: string
      description: |
        area-entered - Event triggered when the device enters the given area

        area-left - Event triggered when the device leaves the given area

        subscription-started - Event triggered when the subscription starts.

        subscription-updated - Event triggered when the subscription is updated.

        subscription-ended - Event triggered when the subscription ends
      enum:
        - org.camaraproject.geofencing-subscriptions.v0.area-entered
        - org.camaraproject.geofencing-subscriptions.v0.area-left
        - org.camaraproject.geofencing-subscriptions.v0.subscription-started
        - org.camaraproject.geofencing-subscriptions.v0.subscription-updated
        - org.camaraproject.geofencing-subscriptions.v0.subscription-ended

    Subscription:
      description: Represents a event-type subscription.
      type: object
      required:
        - sink
        - protocol
        - config
        - types
        - id
        - startsAt
      properties:
        protocol:
          $ref: "#/components/schemas/Protocol"
        sink:
          type: string
          format: uri
          maxLength: 2048
          pattern: ^https:\/\/.+$
          description: The address to which events shall be delivered using the selected protocol.
          example: "https://endpoint.example.com/sink"
        types:
          description: |
            Camara Event types eligible to be delivered by this subscription.
            Note: As of now we enforce to have only event type per subscription.
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: "#/components/schemas/SubscriptionEventType"
        config:
          $ref: "#/components/schemas/ConfigResponse"
        id:
          type: string
          maxLength: 256
          description: The unique identifier of the subscription in the scope of the subscription manager. When this information is contained within an event notification, this concept SHALL be referred as subscriptionId as per Commonalities Event Notification Model.
          example: "1119920371"
        startsAt:
          type: string
          format: date-time
          maxLength: 64
          description: |
            Date when the event subscription will begin/began
            It must follow [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) and must have time zone.
          example: "2023-07-03T12:27:08.312Z"
        expiresAt:
          type: string
          format: date-time
          maxLength: 64
          description: |
            Date when the event subscription will expire. Only provided when `subscriptionExpireTime` is indicated by API client or Telco Operator has specific policy about that.
            It must follow [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) and must have time zone.
          example: "2023-07-03T12:27:08.312Z"
        status:
          type: string
          description: |-
            Current status of the subscription - Management of Subscription State engine is not mandatory for now. Note not all statuses may be considered to be implemented. Details:
              - `ACTIVATION_REQUESTED`: Subscription creation (POST) is triggered but subscription creation process is not finished yet.
              - `ACTIVE`: Subscription creation process is completed. Subscription is fully operative.
              - `INACTIVE`: Subscription is temporarily inactive, but its workflow logic is not deleted.
              - `EXPIRED`: Subscription is ended (no longer active). This status applies when subscription is ended due to `SUBSCRIPTION_EXPIRED` or `ACCESS_TOKEN_EXPIRED` event.
              - `DELETED`: Subscription is ended as deleted (no longer active). This status applies when subscription information is kept (i.e. subscription workflow is no longer active but its meta-information is kept).
          enum:
            - ACTIVATION_REQUESTED
            - ACTIVE
            - EXPIRED
            - INACTIVE
            - DELETED
      discriminator:
        propertyName: protocol
        mapping:
          HTTP: "#/components/schemas/HTTPSubscriptionResponse"

    SubscriptionAsync:
      description: Response for an event-type subscription request managed asynchronously (Creation or Deletion).
      type: object
      required:
        - id
      properties:
        id:
          $ref: "#/components/schemas/SubscriptionId"

    Device:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/Device'

    PhoneNumber:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/PhoneNumber'

    NetworkAccessIdentifier:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/NetworkAccessIdentifier'

    DeviceIpv4Addr:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/DeviceIpv4Address'

    SingleIpv4Addr:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/SingleIpv4Address'

    Port:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/Port'

    DeviceIpv6Address:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/DeviceIpv6Address'

    DeviceResponse:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/DeviceResponse'

    Area:
      type: object
      description: The geofencing area where the monitor is active. This area is specified by API consumers in the subscription request. The same area definition is included in event notifications without any modifications.
      properties:
        areaType:
          $ref: "#/components/schemas/AreaType"
      required:
        - areaType
      discriminator:
        propertyName: areaType
        mapping:
          CIRCLE: "#/components/schemas/Circle"

    AreaType:
      type: string
      description: |
        Type of this area.
        CIRCLE - The area is defined as a circle.
      enum:
        - CIRCLE

    Circle:
      description: Circular area
      allOf:
        - $ref: "#/components/schemas/Area"
        - type: object
          properties:
            center:
              $ref: "#/components/schemas/Point"
            radius:
              type: number
              description: |
                Expected accuracy for the subscription event of device location, in meters from `center`.
                Note: The area surface could be restricted locally depending on regulations. Implementations may enforce a larger minimum radius (e.g. 1000 meters).
              minimum: 1
          required:
            - center
            - radius
      example:
        areaType: CIRCLE
        center:
          latitude: 50.735851
          longitude: 7.10066
        radius: 50000

    Point:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/Point'

    Latitude:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/Latitude'

    Longitude:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/Longitude'

    CloudEvent:
      description: The notification callback.
      allOf:
        - $ref: '../common/CAMARA_event_common.yaml#/components/schemas/CloudEvent'
        - type: object
          properties:
            type:
              $ref: "#/components/schemas/NotificationEventType"
      discriminator:
        propertyName: "type"
        mapping:
          org.camaraproject.geofencing-subscriptions.v0.area-left: "#/components/schemas/EventAreaLeft"
          org.camaraproject.geofencing-subscriptions.v0.area-entered: "#/components/schemas/EventAreaEntered"
          org.camaraproject.geofencing-subscriptions.v0.subscription-started: "#/components/schemas/EventSubscriptionStarted"
          org.camaraproject.geofencing-subscriptions.v0.subscription-updated: "#/components/schemas/EventSubscriptionUpdated"
          org.camaraproject.geofencing-subscriptions.v0.subscription-ended: "#/components/schemas/EventSubscriptionEnded"

    Source:
      $ref: '../common/CAMARA_event_common.yaml#/components/schemas/Source'

    DateTime:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/DateTime'

    SubscriptionId:
      $ref: '../common/CAMARA_event_common.yaml#/components/schemas/SubscriptionId'

    SinkCredential:
      $ref: '../common/CAMARA_event_common.yaml#/components/schemas/SinkCredential'

    AccessTokenCredential:
      $ref: '../common/CAMARA_event_common.yaml#/components/schemas/AccessTokenCredential'

    PrivateKeyJWTCredential:
      $ref: '../common/CAMARA_event_common.yaml#/components/schemas/PrivateKeyJWTCredential'

    HTTPSettings:
      $ref: '../common/CAMARA_event_common.yaml#/components/schemas/HTTPSettings'

    InitiationReason:
      $ref: '../common/CAMARA_event_common.yaml#/components/schemas/InitiationReason'

    UpdateReason:
      $ref: '../common/CAMARA_event_common.yaml#/components/schemas/UpdateReason'

    EventAreaLeft:
      description: Event structure for event when the device leaves the area.
      allOf:
        - $ref: "#/components/schemas/CloudEvent"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/AreaLeft"

    EventAreaEntered:
      description: Event structure for event when the device enters the area.
      allOf:
        - $ref: "#/components/schemas/CloudEvent"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/AreaEntered"

    EventSubscriptionStarted:
      description: Event structure for event subscription started
      allOf:
        - $ref: "#/components/schemas/CloudEvent"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/SubscriptionStarted"

    SubscriptionStarted:
      description: Event detail structure for subscription started event
      type: object
      required:
        - initiationReason
        - subscriptionId
        - area
      properties:
        device:
          $ref: "#/components/schemas/Device"
        area:
          $ref: "#/components/schemas/Area"
        initiationReason:
          $ref: "#/components/schemas/InitiationReason"
        subscriptionId:
          $ref: "#/components/schemas/SubscriptionId"
        initiationDescription:
          description: Description about the start of the subscription.
          type: string
          maxLength: 512

    EventSubscriptionUpdated:
      description: Event structure for event subscription updated
      allOf:
        - $ref: "#/components/schemas/CloudEvent"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/SubscriptionUpdated"

    SubscriptionUpdated:
      description: Event detail structure for subscription updated event
      type: object
      required:
        - area
        - updateReason
        - subscriptionId
      properties:
        device:
          $ref: "#/components/schemas/Device"
        area:
          $ref: "#/components/schemas/Area"
        updateReason:
          $ref: "#/components/schemas/UpdateReason"
        subscriptionId:
          $ref: "#/components/schemas/SubscriptionId"
        updateDescription:
          description: Description about the subscription update.
          type: string
          maxLength: 512

    EventSubscriptionEnded:
      description: Event structure for event subscription ends.
      allOf:
        - $ref: "#/components/schemas/CloudEvent"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/SubscriptionEnded"

    AreaLeft:
      description: |
        Event detail structure for org.camaraproject.geofencing-subscriptions.v0.area-left event.
        Note that the device object is defined as optional and will only to be returned if provided in createGeofencingSubscription.
        If more than one type of device identifier was provided, only one identifier will be returned
        (at implementation choice and with the original value provided in createGeofencingSubscription).
      type: object
      required:
        - area
        - subscriptionId
      properties:
        device:
          $ref: "#/components/schemas/DeviceResponse"
        area:
          $ref: "#/components/schemas/Area"
        subscriptionId:
          $ref: "#/components/schemas/SubscriptionId"

    AreaEntered:
      description: |
        Event detail structure for org.camaraproject.geofencing-subscriptions.v0.area-entered event.
        Note that the device object is defined as optional and will only to be returned if provided in createGeofencingSubscription.
        If more than one type of device identifier was provided, only one identifier will be returned
        (at implementation choice and with the original value provided in createGeofencingSubscription).
      type: object
      required:
        - area
        - subscriptionId
      properties:
        device:
          $ref: "#/components/schemas/DeviceResponse"
        area:
          $ref: "#/components/schemas/Area"
        subscriptionId:
          $ref: "#/components/schemas/SubscriptionId"

    SubscriptionEnded:
      description: |
        Event detail structure for org.camaraproject.geofencing-subscriptions.v0.subscription-ended event.
        Note that the device object is defined as optional and will only to be returned if provided in createGeofencingSubscription.
        If more than one type of device identifier was provided, only one identifier will be returned
        (at implementation choice and with the original value provided in createGeofencingSubscription).
      type: object
      required:
        - area
        - terminationReason
        - subscriptionId
      properties:
        device:
          $ref: "#/components/schemas/DeviceResponse"
        area:
          $ref: "#/components/schemas/Area"
        terminationReason:
          $ref: "#/components/schemas/TerminationReason"
        terminationDescription:
          description: Explanation why a subscription ended or had to end.
          type: string
          maxLength: 512
        subscriptionId:
          $ref: "#/components/schemas/SubscriptionId"

    TerminationReason:
      type: string
      description: |
        - NETWORK_TERMINATED - API server stopped sending notification
        - SUBSCRIPTION_UNPROCESSABLE - Subscription cannot be processed due to some reason, e.g. because the specified area cannot be managed. Useful for asynchronous subscription creation.
        - SUBSCRIPTION_EXPIRED - Subscription expire time (optionally set by the requester) has been reached
        - SUBSCRIPTION_DELETED - Subscription was deleted by the requester
        - MAX_EVENTS_REACHED - Maximum number of events (optionally set by the requester) has been reached
        - ACCESS_TOKEN_EXPIRED - Access Token sinkCredential (optionally set by the requester with credential type `ACCESSTOKEN`) expiration time has been reached
      enum:
        - MAX_EVENTS_REACHED
        - NETWORK_TERMINATED
        - SUBSCRIPTION_UNPROCESSABLE
        - SUBSCRIPTION_EXPIRED
        - SUBSCRIPTION_DELETED
        - ACCESS_TOKEN_EXPIRED

    HTTPSubscriptionRequest:
      description: Subscription request for event delivery over HTTP.
      allOf:
        - $ref: "#/components/schemas/SubscriptionRequest"
        - type: object
          properties:
            protocolSettings:
              $ref: "#/components/schemas/HTTPSettings"

    HTTPSubscriptionResponse:
      description: Subscription response for event delivery over HTTP.
      allOf:
        - $ref: "#/components/schemas/Subscription"
        - type: object
          properties:
            protocolSettings:
              $ref: "#/components/schemas/HTTPSettings"

  responses:
    CreateSubscriptionBadRequest400:
      description: Problem with the client request.
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 400
                  code:
                    enum:
                      - INVALID_ARGUMENT
                      - INVALID_CREDENTIAL
                      - INVALID_PROTOCOL
                      - INVALID_TOKEN
                      - INVALID_SINK
          examples:
            GENERIC_400_INVALID_ARGUMENT:
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: Client specified an invalid argument, request body or query param.
            GENERIC_400_INVALID_PROTOCOL:
              value:
                status: 400
                code: INVALID_PROTOCOL
                message: Only HTTP is supported.
            GENERIC_400_INVALID_CREDENTIAL:
              value:
                status: 400
                code: INVALID_CREDENTIAL
                message: Only Access token or Private key JWT are supported
            GENERIC_400_INVALID_SINK:
              description: Invalid sink value
              value:
                status: 400
                code: INVALID_SINK
                message: sink not valid for the specified protocol
    Generic400:
      $ref: '../common/CAMARA_common.yaml#/components/responses/Generic400'
    SubscriptionIdRequired:
      description: Problem with the client request
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 400
                  code:
                    enum:
                      - INVALID_ARGUMENT
          examples:
            GENERIC_400_INVALID_ARGUMENT:
              summary: Schema validation failed
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: Client specified an invalid argument, request body or query param.
            GENERIC_400_SUBSCRIPTION_ID_REQUIRED:
              summary: The subscription id is required
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: "Expected property is missing: subscriptionId"
    Generic401:
      $ref: '../common/CAMARA_common.yaml#/components/responses/Generic401'
    SubscriptionPermissionDenied403:
      description: Client does not have sufficient permission.
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 403
                  code:
                    enum:
                      - PERMISSION_DENIED
                      - SUBSCRIPTION_MISMATCH
          examples:
            GENERIC_403_PERMISSION_DENIED:
              value:
                status: 403
                code: PERMISSION_DENIED
                message: Client does not have sufficient permissions to perform this action.
            GENERIC_403_TOKEN_MISMATCH:
              value:
                status: 403
                code: SUBSCRIPTION_MISMATCH
                message: Inconsistent access token for requested events subscription.
    Generic403:
      description: Client does not have sufficient permission
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 403
                  code:
                    enum:
                      - PERMISSION_DENIED
          examples:
            GENERIC_403_PERMISSION_DENIED:
              description: Permission denied. OAuth2 token access does not have the required scope or when the user fails operational security
              value:
                status: 403
                code: PERMISSION_DENIED
                message: Client does not have sufficient permissions to perform this action.
    Generic404:
      description: Not found
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 404
                  code:
                    enum:
                      - NOT_FOUND
          examples:
            GENERIC_404_NOT_FOUND:
              description: Resource is not found
              value:
                status: 404
                code: NOT_FOUND
                message: The specified resource is not found.
    Generic410:
      description: Gone
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 410
                  code:
                    enum:
                      - GONE
          examples:
            GENERIC_410_GONE:
              description: Use in notifications flow to allow API Consumer to indicate that its callback is no longer available
              value:
                status: 410
                code: GONE
                message:
                  Access to the target resource is no longer available.
    CreateSubscriptionUnprocessableEntity422:
      description: Unprocessable Entity
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 422
                  code:
                    enum:
                      - MISSING_IDENTIFIER
                      - MULTIEVENT_SUBSCRIPTION_NOT_SUPPORTED
                      - PRIVATE_KEY_JWT_NOT_CONFIGURED
                      - SERVICE_NOT_APPLICABLE
                      - UNNECESSARY_IDENTIFIER
                      - UNSUPPORTED_IDENTIFIER
                      - GEOFENCING_SUBSCRIPTIONS.AREA_NOT_COVERED
                      - GEOFENCING_SUBSCRIPTIONS.INVALID_AREA
          examples:
            GENERIC_422_SERVICE_NOT_APPLICABLE:
              description: Service not applicable for the provided identifier
              value:
                status: 422
                code: SERVICE_NOT_APPLICABLE
                message: The service is not available for the provided identifier.
            GENERIC_422_MISSING_IDENTIFIER:
              description: An identifier is not included in the request and the device or phone number identification cannot be derived from the 3-legged access token
              value:
                status: 422
                code: MISSING_IDENTIFIER
                message: The device cannot be identified.
            GENERIC_422_MULTIEVENT_SUBSCRIPTION_NOT_SUPPORTED:
              value:
                status: 422
                code: MULTIEVENT_SUBSCRIPTION_NOT_SUPPORTED
                message: Multi event types subscription not managed.
            GENERIC_422_PRIVATE_KEY_JWT_NOT_CONFIGURED:
              description: Private key JWT sink credential type is used but no configuration was pre-shared
              value:
                status: 422
                code: PRIVATE_KEY_JWT_NOT_CONFIGURED
                message: No JWK Set configured for PRIVATE_KEY_JWT authentication.
            GENERIC_422_UNNECESSARY_IDENTIFIER:
              description: An explicit identifier is provided when a device or phone number has already been identified from the access token
              value:
                status: 422
                code: UNNECESSARY_IDENTIFIER
                message: The device is already identified by the access token.
            GENERIC_422_UNSUPPORTED_IDENTIFIER:
              description: None of the provided identifiers is supported by the implementation
              value:
                status: 422
                code: UNSUPPORTED_IDENTIFIER
                message: The identifier provided is not supported.
            GEOFENCING_422_AREA_NOT_COVERED:
              summary: The area cannot be covered
              description: The system is not able cover the requested area
              value:
                status: 422
                code: GEOFENCING_SUBSCRIPTIONS.AREA_NOT_COVERED
                message: "Unable to cover the requested area"
            GEOFENCING_422_INVALID_AREA:
              summary: Invalid area
              description: The requested area is too small to be supported by the system.
              value:
                status: 422
                code: GEOFENCING_SUBSCRIPTIONS.INVALID_AREA
                message: "The requested area is too small"
    Generic429:
      description: Too Many Requests
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 429
                  code:
                    enum:
                      - QUOTA_EXCEEDED
                      - TOO_MANY_REQUESTS
          examples:
            GENERIC_429_QUOTA_EXCEEDED:
              description: Request is rejected due to exceeding a business quota limit
              value:
                status: 429
                code: QUOTA_EXCEEDED
                message: Out of resource quota.
            GENERIC_429_TOO_MANY_REQUESTS:
              description: Access to the API has been temporarily blocked due to rate or spike arrest limits being reached
              value:
                status: 429
                code: TOO_MANY_REQUESTS
                message: Rate limit reached.
  examples:
    REQUEST_CIRCLE_AREA_ENTERED:
      description: A sample geofence for entering for a circle area.
      value:
        protocol: "HTTP"
        sink: https://notificationSendServer12.supertelco.com
        types:
          - org.camaraproject.geofencing-subscriptions.v0.area-entered
        config:
          subscriptionDetail:
            device:
              phoneNumber: "+12345678912"
            area:
              areaType: CIRCLE
              center:
                latitude: 50.735851
                longitude: 7.10066
              radius: 2000
          initialEvent: true
          subscriptionMaxEvents: 10
          subscriptionExpireTime: "2024-03-22T05:40:58.469Z"
    REQUEST_CIRCLE_AREA_ENTERED_MULTIPLE_IDENTIFIERS:
      description: A sample geofence for entering for a circle area.
      value:
        protocol: "HTTP"
        sink: https://notificationSendServer12.supertelco.com
        types:
          - org.camaraproject.geofencing-subscriptions.v0.area-entered
        config:
          subscriptionDetail:
            device:
              phoneNumber: "+12345678912"
              ipv4Address:
                publicAddress: 123.234.1.2
                publicPort: 1234
            area:
              areaType: CIRCLE
              center:
                latitude: 50.735851
                longitude: 7.10066
              radius: 2000
          initialEvent: true
          subscriptionMaxEvents: 10
          subscriptionExpireTime: "2024-03-22T05:40:58.469Z"
    CIRCLE_AREA_ENTERED:
      description: The cloud event when a geofence area was entered.
      value:
        id: "123655"
        source: https://notificationSendServer12.supertelco.com
        type: org.camaraproject.geofencing-subscriptions.v0.area-entered
        specversion: "1.0"
        datacontenttype: application/json
        time: 2023-03-22T05:40:23.682Z
        data:
          subscriptionId: 987654321
          device:
            phoneNumber: +123456789
          area:
            areaType: CIRCLE
            center:
              latitude: 50.735851
              longitude: 7.10066
            radius: 2000
    CIRCLE_AREA_LEFT:
      description: The cloud event when a geofence area was left.
      value:
        id: "123655"
        source: https://notificationSendServer12.supertelco.com
        type: org.camaraproject.geofencing-subscriptions.v0.area-left
        specversion: "1.0"
        datacontenttype: application/json
        time: 2023-03-22T05:40:23.682Z
        data:
          subscriptionId: 987654321
          device:
            phoneNumber: +123456789
          area:
            areaType: CIRCLE
            center:
              latitude: 50.735851
              longitude: 7.10066
            radius: 2000

    SUBSCRIPTION_STARTED:
      description: The cloud event when a geofence subscription was started.
      value:
        id: "124003"
        source: https://dataUsageServer.supertelco.com
        type: org.camaraproject.geofencing-subscriptions.v0.subscription-started
        specversion: "1.0"
        datacontenttype: application/json
        data:
          initiationReason: SUBSCRIPTION_CREATED
          subscriptionId: dv10-h556-rt89-1403
          device:
            phoneNumber: +123456789
          area:
            areaType: CIRCLE
            center:
              latitude: 50.735851
              longitude: 7.10066
            radius: 2000
        time: "2024-03-05T15:00:23.682Z"

    SUBSCRIPTION_UPDATED:
      description: The cloud event when a geofence subscription was updated.
      value:
        id: "124003"
        source: https://dataUsageServer.supertelco.com
        type: org.camaraproject.geofencing-subscriptions.v0.subscription-updated
        specversion: "1.0"
        datacontenttype: application/json
        data:
          updateReason: SUBSCRIPTION_ACTIVE
          subscriptionId: dv10-h556-rt89-1403
          device:
            phoneNumber: +123456789
          area:
            areaType: CIRCLE
            center:
              latitude: 50.735851
              longitude: 7.10066
            radius: 2000
        time: "2024-03-05T15:00:23.682Z"

    SUBSCRIPTION_ENDED:
      description: The cloud event when a geofence subscription ended.
      value:
        id: "123655"
        source: https://notificationSendServer12.supertelco.com
        type: org.camaraproject.geofencing-subscriptions.v0.subscription-ended
        specversion: "1.0"
        datacontenttype: application/json
        time: 2023-03-22T05:40:23.682Z
        data:
          subscriptionId: 987654321
          device:
            phoneNumber: +123456789
          area:
            areaType: CIRCLE
            center:
              latitude: 50.735851
              longitude: 7.10066
            radius: 2000
          terminationReason: SUBSCRIPTION_EXPIRED

    SUBSCRIPTION_UNPROCESSABLE:
      description: The cloud event when the subscription process was aborted.
      value:
        id: "123655"
        source: https://notificationSendServer12.supertelco.com
        type: org.camaraproject.geofencing-subscriptions.v0.subscription-ended
        specversion: "1.0"
        datacontenttype: application/json
        time: 2023-03-22T05:40:23.682Z
        data:
          device:
            phoneNumber: +123456789
          area:
            areaType: CIRCLE
            center:
              latitude: 50.735851
              longitude: 7.10066
            radius: 2000
          terminationReason: SUBSCRIPTION_UNPROCESSABLE
          terminationDescription: The requested area cannot be covered by the network.
