openapi: 3.0.3
info:
  title: Device Location Retrieval
  description: |
    This API provides the ability to retrieve a device location.

    # Introduction

    With this API, API consumers can retrieve the area where a certain user device is localized.
    The area provided in the response could be described:
    -  by a circle determined by coordinates (latitude and longitude) and a radius.
    -  by a simple polygon delimited by segments connecting consecutively an array of coordinates (points). The last point connects to the first point to delimit a closed shape bounded with straight sides.

    The retrieved shape depends on the network conditions at the device's location and any of the supported shapes could be received.

    The requester could optionally ask for
     * a freshness of the localization information by providing a `maxAge` ("I want a location not older than 600 seconds").
     * an accuracy of the localization information by providing a `maxSurface` ("I want a location not larger than 1000000 square meters").


    The result accuracy depends on the network's ability and accuracy to locate the device.

    Additionally to location information, the answer will also provide indication about the location time.

    Location retrieval API could be useful in scenarios such as:

    - Fraud protection to ensure a given user is located in the region, country or location authorized for financial transactions
    - Verify the GPS coordinates reported by the app on a device to ensure the GPS was not faked e.g. for content delivery with regional restrictions
    - Contextual-based advertising, to trigger advertising after verifying the device is in the area of interest

    - Smart Mobility (Vehicle/bikes renting): obtain the location of a vehicle/bike to guarantee they are rented correctly

    **Note**: Location is in most jurisdictions considered to be sensitive data and thereby consent by device owner/user must be verified before providing it to the developer.

    # Relevant terms and definitions

    * **Device**: A device refers to any physical entity that can connect to a network and participate in network communication.

    * **Area**: It specifies the geographical surface where a device may be physically located.

    * **Max Age**: Maximum age of the location information which is accepted for the location retrieval (in seconds).

      * Absence of `maxAge` means that "any age" is acceptable for the client. In other words, this is like `maxAge`=infinite. The system will return `lastLocationTime` in the response. If the system is not able to provide location, an error 422 with code LOCATION_RETRIEVAL.UNABLE_TO_LOCATE is sent back.
      * `maxAge`=0 means that a fresh calculation is requested by the client. If the system is not able to provide the fresh location, an error 422 with code LOCATION_RETRIEVAL.UNABLE_TO_FULFILL_MAX_AGE is sent back.

    * **Last Location Time** : Last date and time when the device was localized.

    * **Max Surface**: Maximum surface in square meters which is accepted by the client for the location retrieval.

      * absence of `maxSurface` means that "any surface size" is acceptable for the client.
      * API implementation could specify the minimum acceptable `maxSurface` in the documentation (for example a minimum of 10000 square meters are allowed).
      * If the system is not able to provide an area with a surface acceptable with the client request, an error 422 with code LOCATION_RETRIEVAL.UNABLE_TO_FULFILL_MAX_SURFACE is sent back.
      * Note: if both `maxAge` and `maxSurface` requirements fail, the system can either send back one or the other error code.

    # API Functionality

    The API exposes a single endpoint/operation:

    - `/retrieve` : Retrieve where the device is localized.
     The operation returns:
        * a localization defined either as a circle, with the center specified by the latitude and longitude, and a radius for answer accuracy, or as polygon defined by the array of points delimiting its boundary.
        * a timestamp with the location information freshness.

    <!-- CAMARA:MANDATORY:authorization-and-authentication:BEGIN -->
    # Authorization and authentication

    The "Camara Security and Interoperability Profile" provides details of how an API consumer requests an access token. Please refer to Identity and Consent Management (https://github.com/camaraproject/IdentityAndConsentManagement/) for the released version of the profile.

    The specific authorization flows to be used will be agreed upon during the onboarding process, happening between the API consumer and the API provider, taking into account the declared purpose for accessing the API, whilst also being subject to the prevailing legal framework dictated by local legislation.

    In cases where personal data is processed by the API and users can exercise their rights through mechanisms such as opt-in and/or opt-out, the use of three-legged access tokens is mandatory. This ensures that the API remains in compliance with privacy regulations, upholding the principles of transparency and user-centric privacy-by-design.
    <!-- CAMARA:MANDATORY:authorization-and-authentication:END -->

    <!-- CAMARA:MANDATORY:identifying-device-from-access-token:BEGIN -->
    # Identifying the device from the access token

    This API requires the API consumer to identify a device as the subject of the API as follows:
    - When the API is invoked using a two-legged access token, the subject will be identified from the optional `device` object, which therefore MUST be provided.
    - When a three-legged access token is used however, this optional identifier MUST NOT be provided, as the subject will be uniquely identified from the access token.

    This approach simplifies API usage for API consumers using a three-legged access token to invoke the API by relying on the information that is associated with the access token and was identified during the authentication process.

    ## Error handling:

    - If the subject cannot be identified from the access token and the optional `device` object is not included in the request, then the server will return an error with the `422 MISSING_IDENTIFIER` error code.

    - If the subject can be identified from the access token and the optional `device` object is also included in the request, then the server will return an error with the `422 UNNECESSARY_IDENTIFIER` error code. This will be the case even if the same device is identified by these two methods, as the server is unable to make this comparison.
    <!-- CAMARA:MANDATORY:identifying-device-from-access-token:END -->

    # Multi-SIM scenario handling

    In multi-SIM scenarios, where more than one mobile device is associated with the phone number given as input in the API call (e.g. a smartphone with an associated smartwatch), it might not be possible to uniquely identify the device whose location is to be verified. Check with the API provider what is the expected behaviour when a phone number belonging to a multi-SIM group is used as the device identifier, as the API may response with:

    - an error indicating that that phone number is not supported for this API, or
    - the location of a single device in the multi-SIM group, if one of the devices is considered linked to the main SIM and this concept is supported by the operator, or
    - a location value that combines the location of all the SIMs associated to the requested phone number.

    Possible solutions to make the scenario more deterministic include:

    - Using preferably the authorisation code flow to obtain an access token, which will automatically identify the intended device.
    - Identifying the intended device from a unique identifier for that device, such as its source IP address and port.
    - Check with the API provider whether a unique "secondary" phone number is already associated with each device and use the secondary phone number to identify the intended device if available.

    <!-- CAMARA:MANDATORY:additional-error-responses:BEGIN -->
    # Additional CAMARA error responses

    The list of error codes in this API specification is not exhaustive. Therefore the API specification MAY not document some non-mandatory error statuses as indicated in `CAMARA API Design Guide`.

    Please refer to the `CAMARA_common.yaml` of the Commonalities Release associated to this API version for a complete list of error responses. The applicable Commonalities Release can be identified in the `API Readiness Checklist` document associated to this API version.

    As a specific rule, error `501 - NOT_IMPLEMENTED` can be only a possible error response if it is explicitly documented in the API.
    <!-- CAMARA:MANDATORY:additional-error-responses:END -->

    <!-- CAMARA:MANDATORY:request-body-strictness:BEGIN -->
    # Request body strictness

    This API rejects requests with JSON request bodies that contain properties not declared in this specification, at any nesting level. Unknown properties result in a `400 INVALID_ARGUMENT` response.
    <!-- CAMARA:MANDATORY:request-body-strictness:END -->

    # Further info and support

    (FAQs will be added in a later version of the documentation)
  version: wip
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-camara-commonalities: 0.8.0
externalDocs:
  description: Project documentation at Camara
  url: https://github.com/camaraproject/DeviceLocation
servers:
  - url: '{apiRoot}/location-retrieval/vwip'
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root, defined by the service provider, e.g. `api.example.com` or `api.example.com/somepath`
tags:
  - name: Location Retrieval
    description: Retrieve the location of a device
paths:
  /retrieve:
    post:
      tags:
        - Location Retrieval
      summary: 'Execute location retrieval for a user device'
      description: Retrieve the area where a certain user device is localized.
      operationId: retrieveLocation
      parameters:
        - $ref: '../common/CAMARA_common.yaml#/components/parameters/x-correlator'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RetrievalLocationRequest'
            examples:
              INPUT_PHONE_NUMBER_MAX_AGE:
                summary: Phone number and maxAge
                description: Retrieve location for a device identified by a phone number, providing a maxAge
                value:
                  device:
                    phoneNumber: "+123456789"
                  maxAge: 120
              INPUT_PHONE_NUMBER_MAX_AGE_AND_SURFACE:
                summary: Phone number, maxAge and maxSurface
                description: Retrieve location for a device identified by a phone number, providing a maxAge and maxSurface
                value:
                  device:
                    phoneNumber: "+123456789"
                  maxAge: 120
                  maxSurface: 1000000
              INPUT_IP_ADDRESS_V4:
                summary: IPv4 address without maxAge
                description: Retrieve location for a device identified by an IPv4 address, without an indication for maxAge
                value:
                  device:
                    ipv4Address:
                      publicAddress: 123.234.1.2
                      publicPort: 1234
              INPUT_NO_DEVICE_AND_MAX_AGE:
                summary: Device not provided, only maxAge
                description: The device has to be deducted from token
                value:
                  maxAge: 120
              INPUT_PHONE_NUMBER_IP_ADDRESS_V4:
                summary: Both phone number and IPv4 address, without maxAge
                description: Retrieve location for a device identified both by a phone number and an IPv4 address, without an indication for maxAge
                value:
                  device:
                    phoneNumber: "+123456789"
                    ipv4Address:
                      publicAddress: 123.234.1.2
                      publicPort: 1234
      responses:
        '200':
          description: Location retrieval result
          headers:
            x-correlator:
              $ref: '../common/CAMARA_common.yaml#/components/headers/x-correlator'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
              examples:
                LOCATION_CIRCLE:
                  $ref: "#/components/examples/RETRIEVAL_CIRCLE"
                LOCATION_POLYGON:
                  $ref: "#/components/examples/RETRIEVAL_POLYGON"
                LOCATION_CIRCLE_WITH_DEVICE:
                  $ref: "#/components/examples/LOCATION_CIRCLE_WITH_DEVICE"
        '400':
          $ref: '../common/CAMARA_common.yaml#/components/responses/Generic400'
        '401':
          $ref: '../common/CAMARA_common.yaml#/components/responses/Generic401'
        '403':
          $ref: '#/components/responses/Generic403'
        '404':
          $ref: '#/components/responses/RetrieveLocationNotFound404'
        '422':
          $ref: '#/components/responses/RetrieveLocationUnprocessableEntity422'
      security:
        - openId:
            - location-retrieval:read

components:
  securitySchemes:
    openId:
      description: OpenID Connect authentication
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
  schemas:
    RetrievalLocationRequest:
      description: Request to retrieve the location of a device. Device is not required when using a 3-legged access token, following the rules in the description.
      type: object
      properties:
        device:
          $ref: '../common/CAMARA_common.yaml#/components/schemas/Device'
        maxAge:
          type: integer
          format: int32
          minimum: 0
          maximum: 2147483647
          description: Maximum age of the location information which is accepted for the location retrieval (in seconds). Absence of maxAge means "any age" and maxAge=0 means a fresh calculation.
        maxSurface:
          type: integer
          format: int32
          minimum: 1
          maximum: 2147483647
          description: Maximum surface in square meters which is accepted by the client for the location retrieval. Absence of maxSurface means "any surface size".
          example: 1000000
    Device:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/Device'

    DeviceResponse:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/DeviceResponse'

    Area:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/Area'

    AreaType:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/AreaType'

    Circle:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/Circle'

    Polygon:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/Polygon'

    PointList:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/PointList'

    Point:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/Point'

    Latitude:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/Latitude'

    Longitude:
      $ref: '../common/CAMARA_common.yaml#/components/schemas/Longitude'

    Location:
      type: object
      description: Device location
      required:
        - lastLocationTime
        - area
      properties:
        lastLocationTime:
          $ref: "#/components/schemas/LastLocationTime"
        area:
          $ref: '#/components/schemas/Area'
        device:
          $ref: "#/components/schemas/DeviceResponse"

    LastLocationTime:
      description: Last date and time when the device was localized. It must follow [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) and must have time zone.
      type: string
      format: date-time
      maxLength: 64
      example: "2023-09-07T10:40:52Z"

  responses:
    Generic403:
      description: Forbidden
      headers:
        x-correlator:
          $ref: '../common/CAMARA_common.yaml#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
              - $ref: '../common/CAMARA_common.yaml#/components/schemas/ErrorInfo'
              - type: object
                properties:
                  status:
                    enum:
                      - 403
                  code:
                    enum:
                      - PERMISSION_DENIED
          examples:
            GENERIC_403_PERMISSION_DENIED:
              summary: Permission denied
              description: Permission denied. OAuth2 token access does not have the required scope or when the user fails operational security
              value:
                status: 403
                code: PERMISSION_DENIED
                message: Client does not have sufficient permissions to perform this action.
    RetrieveLocationNotFound404:
      description: Not found
      headers:
        x-correlator:
          $ref: '../common/CAMARA_common.yaml#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
              - $ref: '../common/CAMARA_common.yaml#/components/schemas/ErrorInfo'
              - type: object
                properties:
                  status:
                    enum:
                      - 404
                  code:
                    enum:
                      - IDENTIFIER_NOT_FOUND
          examples:
            GENERIC_404_IDENTIFIER_NOT_FOUND:
              summary: Identifier not found
              description: Some identifier cannot be matched to a device
              value:
                status: 404
                code: IDENTIFIER_NOT_FOUND
                message: Device identifier not found.
    RetrieveLocationUnprocessableEntity422:
      description: Unprocessable Content
      headers:
        x-correlator:
          $ref: '../common/CAMARA_common.yaml#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
              - $ref: '../common/CAMARA_common.yaml#/components/schemas/ErrorInfo'
              - type: object
                properties:
                  status:
                    enum:
                      - 422
                  code:
                    enum:
                      - SERVICE_NOT_APPLICABLE
                      - MISSING_IDENTIFIER
                      - UNSUPPORTED_IDENTIFIER
                      - UNNECESSARY_IDENTIFIER
                      - LOCATION_RETRIEVAL.UNABLE_TO_FULFILL_MAX_AGE
                      - LOCATION_RETRIEVAL.UNABLE_TO_FULFILL_MAX_SURFACE
                      - LOCATION_RETRIEVAL.UNABLE_TO_LOCATE
          examples:
            GENERIC_422_SERVICE_NOT_APPLICABLE:
              summary: Service not applicable
              description: Service not applicable for the provided identifier
              value:
                status: 422
                code: SERVICE_NOT_APPLICABLE
                message: The service is not available for the provided identifier.
            GENERIC_422_MISSING_IDENTIFIER:
              summary: Missing identifier
              description: An identifier is not included in the request and the device or phone number identification cannot be derived from the 3-legged access token
              value:
                status: 422
                code: MISSING_IDENTIFIER
                message: The device cannot be identified.
            GENERIC_422_UNSUPPORTED_IDENTIFIER:
              summary: Unsupported identifier
              description: None of the provided identifiers is supported by the implementation
              value:
                status: 422
                code: UNSUPPORTED_IDENTIFIER
                message: The identifier provided is not supported.
            GENERIC_422_UNNECESSARY_IDENTIFIER:
              summary: Unnecessary identifier
              description: An explicit identifier is provided when a device or phone number has already been identified from the access token
              value:
                status: 422
                code: UNNECESSARY_IDENTIFIER
                message: The device is already identified by the access token.
            LOCATION_RETRIEVAL_422_UNABLE_TO_FULFILL_MAX_AGE:
              summary: Unable to fulfill maxAge
              description: The system is not able to provide the fresh location required by the client
              value:
                status: 422
                code: LOCATION_RETRIEVAL.UNABLE_TO_FULFILL_MAX_AGE
                message: "Unable to provide expected freshness for location"
            LOCATION_RETRIEVAL_422_UNABLE_TO_FULFILL_MAX_SURFACE:
              summary: Unable to fulfill maxSurface
              description: The system is not able to provide accurate acceptable surface required by the client
              value:
                status: 422
                code: LOCATION_RETRIEVAL.UNABLE_TO_FULFILL_MAX_SURFACE
                message: "Unable to provide accurate acceptable surface for location"
            LOCATION_RETRIEVAL_422_UNABLE_TO_LOCATE:
              summary: Unable to locate device
              description: The network cannot locate the device
              value:
                status: 422
                code: LOCATION_RETRIEVAL.UNABLE_TO_LOCATE
                message: "The network is unable to locate the device"
  examples:
    RETRIEVAL_CIRCLE:
      summary: circle-based device location retrieval
      description: The device is localized within a circle with a center at the specified coordinates and a radius of 800 meters.
      value:
        lastLocationTime: "2023-10-17T13:18:23.682Z"
        area:
          areaType: CIRCLE
          center:
            latitude: 45.754114
            longitude: 4.860374
          radius: 800
    RETRIEVAL_POLYGON:
      summary: polygon-based device location retrieval
      description: The device is localized within a polygon delimited by the provided coordinates.
      value:
        lastLocationTime: "2023-10-17T13:18:23.682Z"
        area:
          areaType: POLYGON
          boundary:
            - latitude: 45.754114
              longitude: 4.860374
            - latitude: 45.753845
              longitude: 4.863185
            - latitude: 45.752490
              longitude: 4.861876
            - latitude: 45.751224
              longitude: 4.861125
            - latitude: 45.751442
              longitude: 4.859827
    LOCATION_CIRCLE_WITH_DEVICE:
      summary: circle-based device location retrieval, returning the device identifier used by the implementation
      description: The device is localized within a circle with a center at the specified coordinates and a radius of 800 meters. Response when the request used a 2-legged access token with multiple device identifiers, or possibly only a single device identifier.
      value:
        lastLocationTime: "2023-10-17T13:18:23.682Z"
        area:
          areaType: CIRCLE
          center:
            latitude: 45.754114
            longitude: 4.860374
          radius: 800
        device:
          phoneNumber: "+123456789"
